# Generated by Django 5.0.3 on 2024-03-30 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preoretis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(auto_now_add=True)),
                ('prerety', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task_app.preoretis')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task_app.state')),
            ],
        ),
    ]
