# Generated by Django 5.0.3 on 2024-04-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='prerety',
            new_name='preorety',
        ),
        migrations.AlterField(
            model_name='task',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
